name: Check & Publish Coverage
on:
  pull_request:
  workflow_dispatch:
  push:
    paths: 
      - '.github/workflows/check-coverage.yml'
      - 'codecov.yml'

env:
  python-version: '3.13'

permissions:
  id-token: write

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Test with pytest
        run: |
          uv run --no-default-groups --group cov pytest --cov --cov-report=xml --cov-context=test # Context info not yet supported in cobertura (or any other common format between pytest-cov and codecov.io)
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
