name: Publish Python

on:
  workflow_dispatch:
  push: 
    tags: "v*"

env:
  python-version: '3.13'

jobs:
  python-checks:
    uses: ./.github/workflows/check-python.yml

  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Build
      run: uv build
    - uses: actions/upload-artifact@v4
      with:
        name: pkg
        path: dist/

  publish:
    environment: 
      name: pypi
      url: https://pypi.org/p/ttrpg-dice
    permissions:
      id-token: write
    needs: [python-checks, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: pkg
        path: dist
        merge-multiple: true
    - name: Upload to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1